package com.someone.exchange.network


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Rates(
    @Json(name = "AED")
    val aED: Double = 0.0,
    @Json(name = "AFN")
    val aFN: Double = 0.0,
    @Json(name = "ALL")
    val aLL: Double = 0.0,
    @Json(name = "AMD")
    val aMD: Double = 0.0,
    @Json(name = "ANG")
    val aNG: Double = 0.0,
    @Json(name = "AOA")
    val aOA: Double = 0.0,
    @Json(name = "ARS")
    val aRS: Double = 0.0,
    @Json(name = "AUD")
    val aUD: Double = 0.0,
    @Json(name = "AWG")
    val aWG: Double = 0.0,
    @Json(name = "AZN")
    val aZN: Double = 0.0,
    @Json(name = "BAM")
    val bAM: Double = 0.0,
    @Json(name = "BBD")
    val bBD: Int = 0,
    @Json(name = "BDT")
    val bDT: Double = 0.0,
    @Json(name = "BGN")
    val bGN: Double = 0.0,
    @Json(name = "BHD")
    val bHD: Double = 0.0,
    @Json(name = "BIF")
    val bIF: Double = 0.0,
    @Json(name = "BMD")
    val bMD: Int = 0,
    @Json(name = "BND")
    val bND: Double = 0.0,
    @Json(name = "BOB")
    val bOB: Double = 0.0,
    @Json(name = "BRL")
    val bRL: Double = 0.0,
    @Json(name = "BSD")
    val bSD: Int = 0,
    @Json(name = "BTC")
    val bTC: Double = 0.0,
    @Json(name = "BTN")
    val bTN: Double = 0.0,
    @Json(name = "BWP")
    val bWP: Double = 0.0,
    @Json(name = "BYN")
    val bYN: Double = 0.0,
    @Json(name = "BZD")
    val bZD: Double = 0.0,
    @Json(name = "CAD")
    val cAD: Double = 0.0,
    @Json(name = "CDF")
    val cDF: Double = 0.0,
    @Json(name = "CHF")
    val cHF: Double = 0.0,
    @Json(name = "CLF")
    val cLF: Double = 0.0,
    @Json(name = "CLP")
    val cLP: Double = 0.0,
    @Json(name = "CNH")
    val cNH: Double = 0.0,
    @Json(name = "CNY")
    val cNY: Double = 0.0,
    @Json(name = "COP")
    val cOP: Double = 0.0,
    @Json(name = "CRC")
    val cRC: Double = 0.0,
    @Json(name = "CUC")
    val cUC: Int = 0,
    @Json(name = "CUP")
    val cUP: Double = 0.0,
    @Json(name = "CVE")
    val cVE: Double = 0.0,
    @Json(name = "CZK")
    val cZK: Double = 0.0,
    @Json(name = "DJF")
    val dJF: Double = 0.0,
    @Json(name = "DKK")
    val dKK: Double = 0.0,
    @Json(name = "DOP")
    val dOP: Double = 0.0,
    @Json(name = "DZD")
    val dZD: Double = 0.0,
    @Json(name = "EGP")
    val eGP: Double = 0.0,
    @Json(name = "ERN")
    val eRN: Int = 0,
    @Json(name = "ETB")
    val eTB: Double = 0.0,
    @Json(name = "EUR")
    val eUR: Double = 0.0,
    @Json(name = "FJD")
    val fJD: Double = 0.0,
    @Json(name = "FKP")
    val fKP: Double = 0.0,
    @Json(name = "GBP")
    val gBP: Double = 0.0,
    @Json(name = "GEL")
    val gEL: Double = 0.0,
    @Json(name = "GGP")
    val gGP: Double = 0.0,
    @Json(name = "GHS")
    val gHS: Double = 0.0,
    @Json(name = "GIP")
    val gIP: Double = 0.0,
    @Json(name = "GMD")
    val gMD: Double = 0.0,
    @Json(name = "GNF")
    val gNF: Double = 0.0,
    @Json(name = "GTQ")
    val gTQ: Double = 0.0,
    @Json(name = "GYD")
    val gYD: Double = 0.0,
    @Json(name = "HKD")
    val hKD: Double = 0.0,
    @Json(name = "HNL")
    val hNL: Double = 0.0,
    @Json(name = "HRK")
    val hRK: Double = 0.0,
    @Json(name = "HTG")
    val hTG: Double = 0.0,
    @Json(name = "HUF")
    val hUF: Double = 0.0,
    @Json(name = "IDR")
    val iDR: Double = 0.0,
    @Json(name = "ILS")
    val iLS: Double = 0.0,
    @Json(name = "IMP")
    val iMP: Double = 0.0,
    @Json(name = "INR")
    val iNR: Double = 0.0,
    @Json(name = "IQD")
    val iQD: Double = 0.0,
    @Json(name = "IRR")
    val iRR: Int = 0,
    @Json(name = "ISK")
    val iSK: Double = 0.0,
    @Json(name = "JEP")
    val jEP: Double = 0.0,
    @Json(name = "JMD")
    val jMD: Double = 0.0,
    @Json(name = "JOD")
    val jOD: Double = 0.0,
    @Json(name = "JPY")
    val jPY: Double = 0.0,
    @Json(name = "KES")
    val kES: Double = 0.0,
    @Json(name = "KGS")
    val kGS: Double = 0.0,
    @Json(name = "KHR")
    val kHR: Double = 0.0,
    @Json(name = "KMF")
    val kMF: Double = 0.0,
    @Json(name = "KPW")
    val kPW: Int = 0,
    @Json(name = "KRW")
    val kRW: Double = 0.0,
    @Json(name = "KWD")
    val kWD: Double = 0.0,
    @Json(name = "KYD")
    val kYD: Double = 0.0,
    @Json(name = "KZT")
    val kZT: Double = 0.0,
    @Json(name = "LAK")
    val lAK: Double = 0.0,
    @Json(name = "LBP")
    val lBP: Double = 0.0,
    @Json(name = "LKR")
    val lKR: Double = 0.0,
    @Json(name = "LRD")
    val lRD: Double = 0.0,
    @Json(name = "LSL")
    val lSL: Double = 0.0,
    @Json(name = "LYD")
    val lYD: Double = 0.0,
    @Json(name = "MAD")
    val mAD: Double = 0.0,
    @Json(name = "MDL")
    val mDL: Double = 0.0,
    @Json(name = "MGA")
    val mGA: Double = 0.0,
    @Json(name = "MKD")
    val mKD: Double = 0.0,
    @Json(name = "MMK")
    val mMK: Double = 0.0,
    @Json(name = "MNT")
    val mNT: Double = 0.0,
    @Json(name = "MOP")
    val mOP: Double = 0.0,
    @Json(name = "MRU")
    val mRU: Double = 0.0,
    @Json(name = "MUR")
    val mUR: Double = 0.0,
    @Json(name = "MVR")
    val mVR: Double = 0.0,
    @Json(name = "MWK")
    val mWK: Double = 0.0,
    @Json(name = "MXN")
    val mXN: Double = 0.0,
    @Json(name = "MYR")
    val mYR: Double = 0.0,
    @Json(name = "MZN")
    val mZN: Double = 0.0,
    @Json(name = "NAD")
    val nAD: Double = 0.0,
    @Json(name = "NGN")
    val nGN: Double = 0.0,
    @Json(name = "NIO")
    val nIO: Double = 0.0,
    @Json(name = "NOK")
    val nOK: Double = 0.0,
    @Json(name = "NPR")
    val nPR: Double = 0.0,
    @Json(name = "NZD")
    val nZD: Double = 0.0,
    @Json(name = "OMR")
    val oMR: Double = 0.0,
    @Json(name = "PAB")
    val pAB: Int = 0,
    @Json(name = "PEN")
    val pEN: Double = 0.0,
    @Json(name = "PGK")
    val pGK: Double = 0.0,
    @Json(name = "PHP")
    val pHP: Double = 0.0,
    @Json(name = "PKR")
    val pKR: Double = 0.0,
    @Json(name = "PLN")
    val pLN: Double = 0.0,
    @Json(name = "PYG")
    val pYG: Double = 0.0,
    @Json(name = "QAR")
    val qAR: Double = 0.0,
    @Json(name = "RON")
    val rON: Double = 0.0,
    @Json(name = "RSD")
    val rSD: Double = 0.0,
    @Json(name = "RUB")
    val rUB: Double = 0.0,
    @Json(name = "RWF")
    val rWF: Double = 0.0,
    @Json(name = "SAR")
    val sAR: Double = 0.0,
    @Json(name = "SBD")
    val sBD: Double = 0.0,
    @Json(name = "SCR")
    val sCR: Double = 0.0,
    @Json(name = "SDG")
    val sDG: Double = 0.0,
    @Json(name = "SEK")
    val sEK: Double = 0.0,
    @Json(name = "SGD")
    val sGD: Double = 0.0,
    @Json(name = "SHP")
    val sHP: Double = 0.0,
    @Json(name = "SLL")
    val sLL: Double = 0.0,
    @Json(name = "SOS")
    val sOS: Double = 0.0,
    @Json(name = "SRD")
    val sRD: Double = 0.0,
    @Json(name = "SSP")
    val sSP: Double = 0.0,
    @Json(name = "STD")
    val sTD: Double = 0.0,
    @Json(name = "STN")
    val sTN: Double = 0.0,
    @Json(name = "SVC")
    val sVC: Double = 0.0,
    @Json(name = "SYP")
    val sYP: Double = 0.0,
    @Json(name = "SZL")
    val sZL: Double = 0.0,
    @Json(name = "THB")
    val tHB: Double = 0.0,
    @Json(name = "TJS")
    val tJS: Double = 0.0,
    @Json(name = "TMT")
    val tMT: Double = 0.0,
    @Json(name = "TND")
    val tND: Double = 0.0,
    @Json(name = "TOP")
    val tOP: Double = 0.0,
    @Json(name = "TRY")
    val tRY: Double = 0.0,
    @Json(name = "TTD")
    val tTD: Double = 0.0,
    @Json(name = "TWD")
    val tWD: Double = 0.0,
    @Json(name = "TZS")
    val tZS: Int = 0,
    @Json(name = "UAH")
    val uAH: Double = 0.0,
    @Json(name = "UGX")
    val uGX: Double = 0.0,
    @Json(name = "USD")
    val uSD: Int = 0,
    @Json(name = "UYU")
    val uYU: Double = 0.0,
    @Json(name = "UZS")
    val uZS: Double = 0.0,
    @Json(name = "VES")
    val vES: Double = 0.0,
    @Json(name = "VND")
    val vND: Double = 0.0,
    @Json(name = "VUV")
    val vUV: Double = 0.0,
    @Json(name = "WST")
    val wST: Double = 0.0,
    @Json(name = "XAF")
    val xAF: Double = 0.0,
    @Json(name = "XAG")
    val xAG: Double = 0.0,
    @Json(name = "XAU")
    val xAU: Double = 0.0,
    @Json(name = "XCD")
    val xCD: Double = 0.0,
    @Json(name = "XDR")
    val xDR: Double = 0.0,
    @Json(name = "XOF")
    val xOF: Double = 0.0,
    @Json(name = "XPD")
    val xPD: Double = 0.0,
    @Json(name = "XPF")
    val xPF: Double = 0.0,
    @Json(name = "XPT")
    val xPT: Double = 0.0,
    @Json(name = "YER")
    val yER: Double = 0.0,
    @Json(name = "ZAR")
    val zAR: Double = 0.0,
    @Json(name = "ZMW")
    val zMW: Double = 0.0,
    @Json(name = "ZWL")
    val zWL: Int = 0
)