name: Build the app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BRANCH_NAME: ${{ github.ref_name }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  check:
    if: ${{ startsWith(github.actor, 'dependabot') }}
    environment: Development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: gradle

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v3

    - name: Build debug APK
      run: ./gradlew assembleDebug

  ktlint:
    if: ${{ ! startsWith(github.actor, 'dependabot') }}
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Kotlin linter
        run: ./gradlew ktlintCheck

  build:
    needs: ktlint
    environment: Development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: gradle

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v3

    - name: Decrypt the keystore for signing
      run: |
        echo "${{ secrets.KEYSTORE_ENCRYPTED }}" > keystore.asc
        gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD }}" --batch keystore.asc > keystore.jks

    - name: Decrypt the config for Google Services
      run: |
        echo "${{ secrets.GOOGLE_ENCRYPTED }}" > google-services.asc
        gpg -d --passphrase "${{ secrets.GOOGLE_PASSWORD }}" --batch google-services.asc > app/google-services.json

    - name: Build release Github APK
      run: ./gradlew assembleGithub

    - name: Build release GooglePlay APK
      run: ./gradlew assembleGoogleplay

    - name: Upload Github APK
      uses: actions/upload-artifact@v4
      with:
        name: ark-rate-github
        path: ./app/build/outputs/apk/github/release/ark-rate-github-release.apk

    - name: Upload GooglePlay APK
      uses: actions/upload-artifact@v4
      with:
        name: ark-rate-googleplay
        path: ./app/build/outputs/apk/googleplay/release/ark-rate-googleplay-release.apk

  lint:
    needs: build
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Run linter
        run: ./gradlew lint

      - uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: ./app/build/reports/*.html

