name: Fetch Exchange Rates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
    
env:
  APP_ID: ${{ secrets.APP_ID }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          ref: exchange-rates
      
    #  - name: Set up Python
   #     uses: actions/setup-python@v4
   #     with:
   #       python-version: '3.x'

      #- name: Install dependencies
     #   run: |
     #     pip install --upgrade pip
     #     pip install requests
          
      #- name: Run fetch-rates.py script
      #  run: python fetch-rates.py
        
      - name: Fetch fiat
        run: curl -X GET "https://openexchangerates.org/api/latest.json?app_id=${{ secrets.APP_ID }}" --output core/data/src/main/assets/fiat-rates.json
          
      - name: cat file
        run: cat core/data/src/main/assets/fiat-rates.json
      
     # - name: Move JSON file to assets directory
       # run: mv crypto-rates.json core/data/src/main/assets/
       
      - name: Push to GitHub
        run: |
          git config --global user.email "bot@ark-builders.dev"
          git config --global user.name "ARK Builders Bot"
          
          git add core/data/src/main/assets/fiat-rates.json
          #git add core/data/src/main/assets/crypto-rates.json
          
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automatic update of rates"
            git pull origin exchange-rates --no-edit
            git push origin exchange-rates
          fi
