name: Release the app

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Development
    env:
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v3

    - name: Decrypt the keystore for signing
      run: |
        echo "${{ secrets.KEYSTORE_ENCRYPTED }}" > keystore.asc
        gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD }}" --batch keystore.asc > keystore.jks

    - name: Decrypt the config for Google Services
      run: |
        echo "${{ secrets.GOOGLE_ENCRYPTED }}" > google-services.asc
        gpg -d --passphrase "${{ secrets.GOOGLE_PASSWORD }}" --batch google-services.asc > app/google-services.json

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./app/build/outputs/apk/*/release/*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
